packages:
  - eslint-config/*
  - prettier-config/*
  - commitlint-config/*
  - stylelint-config/*
  - internal/*
  - internal/lint-configs/*
catalog:
  '@commitlint/cli': ^19.6.1
  '@commitlint/config-conventional': ^19.6.0
  '@types/eslint': ^9.6.1
  '@eslint/js': ^9.17.0
  '@typescript-eslint/eslint-plugin': ^8.19.1
  '@typescript-eslint/parser': ^8.19.1
  '@stylistic/stylelint-plugin': ^3.1.1
  commitlint-plugin-function-rules: ^4.0.1
  cross-env: ^7.0.3
  cspell: ^8.17.1
  cz-git: ^1.11.0
  czg: ^1.11.0
  lint-staged: ^15.3.0
  eslint: ^9.17.0
  eslint-config-turbo: ^2.3.3
  eslint-plugin-command: ^0.2.7
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-jsdoc: ^50.6.1
  eslint-plugin-jsonc: ^2.18.2
  eslint-plugin-n: ^17.15.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.6.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-unused-imports: ^4.1.4
  globals: ^15.14.0
  '@vitest/eslint-plugin': ^1.1.25
  eslint-plugin-vue: ^9.32.0
  postcss: ^8.4.49
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.3
  postcss-scss: ^4.0.9
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.9
  publint: ^0.2.12
  stylelint: ^16.12.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.5.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  stylelint-scss: ^6.10.0
  vite: ^6.0.11
  vue-eslint-parser: ^9.4.3
  husky: ^9.1.7
  is-ci: ^4.1.0
  jsonc-eslint-parser: ^2.4.0
  rimraf: ^6.0.1
